version: 1.0.0
jobs:
  build_windows:
    docker:
      - image: electronuserland/builder:wine
    steps:
      - checkout
      - run:
          command: |
            echo 'export NVM_DIR="/opt/circleci/.nvm"' >> $BASH_ENV
            echo ' [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"' >> $BASH_ENV
      - run: nvm install 16.20.0
      - run: node -v
      - run: npm -v
      - run: nvm alias default 16.20.0
      - run: nvm use 16.20.0
      - run: node -v
      - run: npm -v
      - run: npm install && npm run build
      - store_artifacts:
          path: /root/project/build

workflows:
  version: 2
  build:
    jobs:
      - build_windows
